### ISSUE TITLE
急需一个flutter版的fastboard

### ISSUE THREAD

**Issue by shiguanghuxian** [netless-io/fastboard#10]
希望实现不要使用webview，而是使用安卓和ios的sdk进行封装

**Comment by l1shen** [comment]
目前有计划做 flutter 版本，但是交付时间还没有确定
另外，安卓和 ios 版本也是用的 webview

**Comment by shiguanghuxian** [comment]
那有没有大概交付时间没，这边技术栈是flutter，或者可以释放一个预览版，可以先行开发使用

**Comment by l1shen** [comment]
https://github.com/netless-io/fastboard_flutter

目前我们有一个正在开发中的最小可用的先行版，可以先看下

**Comment by shiguanghuxian** [comment]
好的，谢谢
