### ISSUE TITLE
元素之间连接

### ISSUE THREAD

**Issue by istommao** [netless-io/fastboard#16]
会开发元素之间互相链接的功能吗

**Comment by Leooeloel** [comment]
<img width="586" alt="企业微信截图_e62f4c95-1c23-4637-97ac-589e6c5e97cd" src="https://user-images.githubusercontent.com/29906716/199430743-26281007-69be-44ec-bc1d-30abbd25e43c.png">

你说的是这种连接线？可以简单描述一下你的使用场景吗？

**Comment by Leooeloel** [comment]
我们互动白板定位于侧重书写、资料展示，也就是传统教育场景；和侧重协作的互动白板是不同的，可能短时间内我们没有太多精力去做这些，另外像 miro 这类白板在协作方面已经做的很好了，很感谢你的建议～
