### ISSUE TITLE
本地在flat项目中集成时报window.__netlessJavaScriptLoader was override

### ISSUE THREAD

**Issue by qimingzizeinan** [netless-io/fastboard#19]
本地build之后，在flat项目中pnpm link打包后的fastboard，会报window.__netlessJavaScriptLoader was override这个错误.

**Comment by hyrious** [comment]
这个报错通常是由于项目里存在两个或以上 white-web-sdk 造成的，建议检查一下 package.json 和 lockfile，可以借助 `pnpm why -r white-web-sdk` 命令。

**Comment by qimingzizeinan** [comment]
非常感谢。推荐使用发布了之后install这种方式么？

**Comment by qimingzizeinan** [comment]
我注意到flat中集成的fastboard的版本是1.0.0的，如果我做二次开发是要使用fastboard的1.0这个分支么？同时还有另外一个问题。运行pnpm run dev:ui会爆一个错误。将@sveltejs/vite-plugin-svelte的版本改以为1之后就可以正常运行了。

**Comment by hyrious** [comment]
> 推荐使用发布了之后install这种方式么？

基本上所有库都是推荐这么用吧。

> 如果我做二次开发是要使用 fastboard 的1.0这个分支么？

二开 Flat 的话是的。

> 运行pnpm run dev:ui会爆一个错误

这个 svelte 插件不让在 vite.config.ts 里直接 import 用了，我刚更新了一下配置。

**Comment by qimingzizeinan** [comment]
非常感谢。
