### ISSUE TITLE
Uncaught (in promise) TypeError: Tippy.setDefaultProps is not a function  at ./node_modules/@netless/fastboard-ui/dist/index.js

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#21]

**Comment by hyrious** [comment]
This means that your bundler decides to bundle the CJS format of fastboard, and the CJS format does not work well -- https://github.com/netless-io/fastboard/blob/main/CHANGELOG.md#unreleased

Modern bundlers should choose the [`module`](https://github.com/netless-io/fastboard/blob/ef22e0f9aed39b3241ba2a08775783b516c0da53/packages/fastboard/package.json#L23) file as pointed in package.json, which is in ESM format for fastboard. I'd suggest you to use another bundler like [esbuild](https://esbuild.github.io) to bundle this library.

**Comment by kush4545** [comment]
Hey @hyrious Thanks for the solution, but the issue is I am using razzle bundle and can not use esbuild now in my project. so is there any other alternative or any other way for this?

**Comment by hyrious** [comment]
Sorry but we do not plan to keep supporting any webpack4 based bundler in favor of the movement to ESM of the whole community.
