### ISSUE TITLE
I am using netless/fastboard-react in library and I encountered this error, ./node_modules/remitter/dist/remitter.mjs 3:5 Module parse failed: Unexpected token (3:5) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#23]
As soon as I comment my fastboard, it will work fine.

**Comment by hyrious** [comment]
It looks like your bundler either cannot recognize .mjs files (which are javascript files) or cannot parse the "class field" syntax (ES2022):

```js
// source code of remitter.mjs
var Remitter = class {
  _l = /* @__PURE__ */ new Map(); // <- failed to parse this code
```

This means that your bundler (or loader) is too old to work with some libraries that fastboard is depending on. I'd recommend you to use a more modern bundler like [esbuild](https://esbuild.github.io) or [vite](https://vitejs.dev) to continue.

**Comment by hyrious** [comment]
I'm closing it as it seems not an issue with fastboard, but with the bundler.
