### ISSUE TITLE
How to add local system image and video in apps toolbar

### ISSUE THREAD

**Issue by AnshuBansal6** [netless-io/fastboard#26]
So, We have option of Image and Media in Apps inside whiteboard. Currently if we pass url it is working fine.

Is there any way we can popup the local system library from where user can pick image or video which they want to use

**Comment by hyrious** [comment]
Fastboard itself does not have / provide any uploading function or object storage. You have to deploy a server and do uploading by yourself.

The uploading task is quite common that you will get many examples if you search on the web. Here I just put one simple way:

```js
// on click "upload image":
var input = document.createElement('input')
input.type = "file"
input.style.diaplay = "none"
document.body.append(input)
input.click()
input.onchange = () => upload(input.files)

const upload = async (files) => {
  if (files && files[0]) {
    var file = files[0]
    var url = await upload_and_get_url(file)
    fastboard.insertImage(url)
  }
}
```

**Comment by hyrious** [comment]
I'm closing this issue as uploading images and videos is not the job of Fastboard. Customers should implement the uploading function with their own object storage services.
