### ISSUE TITLE
how can use google doc with help of link (just as pdf)

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#29]
const appId = await fastboard.manager.addApp({
  kind: "EmbeddedPage",
  options: { title: "Google Docs" },
  attributes: {
    src: "https://docs.google.com/document/d/1bd4SRb5BmTUjPGrFxU2V7KI2g_mQ-HQUBxKTxsEn5e4/edit?usp=sharing",
  },
});

This I am facing some version problem

**Comment by hyrious** [comment]
I don't understand. Did you encounter some error messages in your console? If so you can post them here to aid me know the issue.

If you failed to load the EmbeddedPage app from the default CDN link, you can try to use another one. I have answered this question before: https://github.com/netless-io/fastboard/issues/25#issuecomment-1691109739

**Comment by kush4545** [comment]
This is the error:
Refused to frame 'https://contacts.google.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://docs.google.com".

I am using the same doc which is in your git repo:
const appId = await fastboard.manager.addApp({
  kind: "EmbeddedPage",
  options: { title: "Google Docs" },
  attributes: {
    src: "https://docs.google.com/document/d/1bd4SRb5BmTUjPGrFxU2V7KI2g_mQ-HQUBxKTxsEn5e4/edit?usp=sharing",
  },
});

**Comment by hyrious** [comment]
The error said that `contacts.google.com` cannot be displayed in an iframe whose ancestors have restricted the access to only allow pages at `docs.google.com`. The restriction seems to be set by Google Docs itself.

```html
EmbeddedPage App:
  <iframe src="docs.google.com">
    <iframe src="contacts.google.com">
      BOOM!
    </iframe>
  </iframe>
```

Which is to say, Google Docs prevents some functions to work in the context of iframe. You have to live with it.

**Comment by kush4545** [comment]
issue is resolved
