### ISSUE TITLE
when we are using fastboard and installing it in repo then this new error is coming

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#30]
Uncaught TypeError: Cannot set properties of undefined (setting 'type')
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass

**Comment by hyrious** [comment]
This is probably a bundler's config issue. More details see: https://github.com/josdejong/mathjs/issues/3022

I can't help much in these kinds of issues as I don't know webpack very much too.

**Comment by hyrious** [comment]
In case you do not use the legacy PPT function in `white-web-sdk` (new customers should prefer using the "projector" conversion service), you can invalidate the `mathjs` package in your dependencies tree to avoid this issue. I have published a new package to help doing this:

https://github.com/netless-io/nolyfill-mathjs

Please refer to its README to solve the issue.
